#!/bin/sh

trap tmux-session-cleanup EXIT HUP

tmux-session-cleanup()
{
    if [ -L "${USERSOCKET}" ]; then
        echo "Removing ${USERSOCKET}"
        rm -f "${USERSOCKET}"
    fi
}



USERSOCKET="/tmp/.wrap_auth_sock-${USER}"

if [ -n "$TMUX" ]; then
    # Already in tmux session, do nada
    echo "Already in tmux session"
    exit 1
fi


# Set up ssh agent forwarding
# TODO: This could test for existing link and do something different if one exists.

if [ -L "${USERSOCKET}" ] && [ -e "${USERSOCKET}" ]; then
    echo "Refusing to overwrite existing link"
    exit 1
fi

if [ -n  "$SSH_TTY" ] && [ -n "${SSH_AUTH_SOCK}" ]; then # Ssh connection and agent forwarding is on
    ln -sf "$SSH_AUTH_SOCK" "${USERSOCKET}" # Create the symbolic link
    export SSH_AUTH_SOCK="$USERSOCKET" # Set SSH_AUTH_SOCK to the link
fi


TMUX_SESSION=$1

: ${TMUX_SESSION:="sshwrap"}

export STY="tmux-${TMUX_SESSION}"

#exec tmux new-session -A -s "${TMUX_SESSION}"

tmux new-session -A -s "${TMUX_SESSION}"

