#!/bin/sh

# Driver program to wrap together many different scripts of the
# sysupdate suite


LC_ALL=C
unset SHELL

# TODO: Reset PATH to something safe.

usage() { 
	cat << EOF
Usage: $0 command [options]

Commands:
    bootstrap       -- Bootstrap a buildjail
    buildsources    -- Buildworld/buildkernel with sources set up in the buildjail
    newcleanjail    -- Sets up a new clean jail using the objects produced with buildsources
    newsources      -- Setup new sources in a buildjail
    updatehost      -- Update host system with the objects produced with buildsources
    updatebuildjail -- Update a buildjail with the objects produced with buildsources

EOF
	exit 1
}


# Only -h for help for now.
while getopts "h" FLAG; do
    case "${FLAG}" in
    h) usage;;
    *) usage;;
    esac
done

shift $((OPTIND-1))

[ $# -lt 1 ] && usage

SYSUPDATEPATH=`realpath $0`
SYSUPDATEPREFIX=${SYSUPDATEPATH%\/bin/*}
#SYSUPDATEPREFIX=${SYSUPDATEPREFIX}/share/rdznl-sysupdate

CMD=$1
shift
CMD_ENV="PATH=${PATH}"

# Pass this to the scripts so they don't have to figure it out themselves.
CMD_ENV="SYSUPDATEPREFIX=${SYSUPDATEPREFIX} ${CMD_ENV}"

# Handle special-case commands first.
case "${CMD}" in
	version)
		echo "${SYSUPDATE_VERSION}"
		exit 0
		;;
	help)
		usage
		;;
esac

case "${CMD}" in
	bootstrap|buildsources|newcleanjail|newsources|updatebuildjail|updatehost)
		;;
	*)
		echo "Unknown command '${CMD}'"
		usage
		;;
esac

exec env -i ${CMD_ENV} /bin/sh "${SYSUPDATEPREFIX}/share/rdnzl-sysupdate/${CMD}.sh" $@
